### ISSUE TITLE
Download distance on windows 11

### ISSUE THREAD

**Issue by litte-charro** [DistanceDevelopment/distance-bugs#211] opened 2022-10-25 17:02 UTC
Hi, 

Is it possible to download distance on windows 11? I have a newer computer and I'm not able to open the program. I get a message that it can't find an app to run the software. I even tried setting the compatibility setting to xp or windows 7 and it made no difference. I appreciate whatever help I can get!

**Comment by erex** [comment] 2022-10-25 19:03
Thanks for your message.  Is it possible for you to upload  a screenshot of the message you are getting.  The programme that you download from our website is an installation programme.  Running the programme will install the Distance programme onto your computer.

I'm guessing your computer might be refusing to let you install the programme, complaining it lacks a Microsoft certificate.  You can install by clicking "install anyway".

We can confirm this is the issue by seeing the message your computer generates.

**Comment by LHMarshall** [comment] 2022-11-01 10:32
@erex I'm going to close this. I had a query about the same thing via the distance@ E-mail on the same day and we resolved it by a repeated download via dropbox (of the same installation file). I think something went wrong with the initial downloading of the file. 

@litte-charro if that wasn't you please do get in touch again if the problem is persisting for you.

**Closed by LHMarshall** 2022-11-01 10:32 UTC
