### ISSUE TITLE
Can't open distance project

### ISSUE THREAD

**Issue by doogiegreen** [DistanceDevelopment/distance-bugs#175] opened 2017-01-31 10:43 UTC
Hi

I've been sent a distance project (.dst file) and I'm trying to open it but I get a pop up saying "Confirm open from non-local drive" and when I click Yes confirming that I want to open the project directly from it's current location I'm given the error "Cannot Open Project, The data folder H:\Documents\Project\Green Toucan 1.dat\ does not exist."

Hope you can help!

Thanks

**Comment by erex** [comment] 2017-01-31 10:51
DoogieGreen

Your problem is not a bug in the software.  What you have received is not a complete Distance project, but only a piece.  Chapter 4 of the Users Guide describes how Distance projects are stored, with this schematic
![image](https://cloud.githubusercontent.com/assets/330744/22461845/e0ad9834-e7a2-11e6-828a-86aa814bfa8f.png)

As you can see, there is much more than simply the `.dst` file

You need to ask your collaborator to archive the Toucan project using the "File | Export project" command from the main menu.  That will produce a `.zip` file containing all the correct elements that you can then extract on your computer (reproducing the file structure I showed above), for your analysis.

**Comment by LHMarshall** [comment] 2017-01-31 11:33
Closing this as not a bug

**Closed by LHMarshall** 2017-01-31 11:33 UTC
